name: CI for check dependencies
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      
      - name: Install dependencies
        run: npm ci
        
      - run: npm run build

      - name: Verify dist matches committed files
        run: |
          # Show a concise diff if there are changes
          if ! git diff --quiet -- dist || [ -n "$(git ls-files --others --exclude-standard dist)" ]; then
            echo "::error::Built dist differs from what's committed."
            echo "Run 'npm ci && npm run build' locally and commit the updated dist/."
            echo ""
            echo "Changed tracked files:"
            git diff --name-status -- dist || true
            echo ""
            echo "Untracked files:"
            git ls-files --others --exclude-standard dist || true
            exit 1
          fi
